networks:
  consilient-net:
    driver: bridge
    name: consilient-net
  ollama-docker:
    external: false

volumes:
  consilient-mssql-data:
  ollama_data:

services:

  loki:
    image: grafana/loki:latest
    container_name: consilient.logging.loki.container
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - consilient-net
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: consilient.logging.promtail.container
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro  # Add this
      - /var/run/docker.sock:/var/run/docker.sock:ro              # Add this
    command: -config.file=/etc/promtail/config.yml
    networks:
      - consilient-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: consilient.logging.grafana.container
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki
    networks:
      - consilient-net
    restart: unless-stopped

  db:
    image: ${DOCKER_REGISTRY-}consilientdb
    container_name: consilient.dbs.container
    build:
      context: .
      dockerfile: Db/Dockerfile
    ports:
      - "1434:1433"
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    command: -databases consilient_hangfire consilient_main
    volumes:
        - consilient-mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"${SA_PASSWORD}\" -C -Q \"SELECT 1\""]
      interval: 10s
      retries: 10
      start_period: 60s
      timeout: 3s
    networks:
      - consilient-net
    restart: unless-stopped

  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: consilient.ai.ollama.container
    ports:
      - 7869:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: consilient.ai.ollama.webui.container
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "8070:8080"
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://ollama:11434 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=valiantlynx AI
      - WEBUI_URL=http://localhost:8070
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-docker

  consilient.webapp:
    image: ${DOCKER_REGISTRY-}consilientwebapp
    container_name: consilient.apps.webapp.container
    build:
      context: ..
      dockerfile: Consilient.WebApp/Dockerfile
      args:
        BUILD_CONFIGURATION: "Debug"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - consilient-net

  consilient.api:
    image: ${DOCKER_REGISTRY-}consilientapi
    container_name: consilient.apps.api.container
    build:
      context: ..
      dockerfile: Consilient.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: "Debug"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "8090:8090"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - consilient-net

  consilient.backgroundhost:
    image: ${DOCKER_REGISTRY-}consilientbackgroundhost
    container_name: consilient.apps.backgroundhost.container
    build:
      context: ..
      dockerfile: Consilient.BackgroundHost/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8092"
    ports:
      - "8092:8092"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - consilient-net
    restart: unless-stopped