networks:
  consilient-net:
    driver: bridge
    name: consilient-net
  ollama-docker:
    external: false

volumes:
  consilient-mssql-data:
  ollama_data:

services:

  loki:
    image: grafana/loki:latest
    container_name: consilient.logging.loki.container
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - consilient-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: consilient.logging.grafana.container
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki
    networks:
      - consilient-net
    restart: unless-stopped

  db:
    image: ${DOCKER_REGISTRY-}consilientdb
    container_name: consilient.dbs.container
    build:
      context: ..
      dockerfile: Databases/Dockerfile
    ports:
      - "1434:1433"
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    command: -databases consilient_hangfire consilient_main
    volumes:
        - consilient-mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"${SA_PASSWORD}\" -C -Q \"SELECT 1\""]
      interval: 10s
      retries: 10
      start_period: 60s
      timeout: 3s
    networks:
      - consilient-net
    restart: unless-stopped

  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: consilient.ai.ollama.container
    ports:
      - 7869:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker
      - consilient-net

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: consilient.ai.ollama.webui.container
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "8070:8080"
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://ollama:11434 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=Consilient AI
      - WEBUI_URL=http://localhost:8070
      - WEBUI_SECRET_KEY=${OLLAMA_WEBUI_SECRET_KEY}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-docker

  consilient.webapp2:
    image: ${DOCKER_REGISTRY-}consilientwebapp2
    container_name: consilient.apps.webapp2.container
    build:
      context: ../Consilient.WebApp2
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: "Debug"
    environment:
      APP_API_BASE_URL: "https://localhost:8091"
      APP_ENV: "development"
      APP_ENABLE_DEBUG_MODE: "true"
      APP_USE_MOCK_SERVICES: "false"
      APP_ENABLE_EXTERNAL_LOGIN_MOCK: "false"
    ports:
      - "8082:80"
    networks:
      - consilient-net
    restart: unless-stopped

  consilient.webapp2.dev:
    image: ${DOCKER_REGISTRY-}consilientwebapp2-dev
    container_name: consilient.apps.webapp2.dev.container
    build:
      context: ../Consilient.WebApp2
      dockerfile: Dockerfile.dev
    environment:
      APP_API_BASE_URL: "https://localhost:8091"
      APP_ENV: "development"
      APP_ENABLE_DEBUG_MODE: "true"
    volumes:
      - ../Consilient.WebApp2/src:/app/src
      - ../Consilient.WebApp2/public:/app/public
      - /app/node_modules
    ports:
      - "8083:5173"
    networks:
      - consilient-net
    profiles:
      - dev

  consilient.api:
    image: ${DOCKER_REGISTRY-}consilientapi
    container_name: consilient.apps.api.container
    build:
      context: ..
      dockerfile: Consilient.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: "Debug"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:8091"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/consilient-api.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "${DEV_CERT_PASSWORD}"
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro
      - ../_tmp:/app/uploads
    ports:
      - "8091:8091"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - consilient-net
    restart: unless-stopped

  consilient.backgroundhost:
    image: ${DOCKER_REGISTRY-}consilientbackgroundhost
    container_name: consilient.apps.backgroundhost.container
    build:
      context: ..
      dockerfile: Consilient.BackgroundHost/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:8092"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/consilient-api.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "${DEV_CERT_PASSWORD}"
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro
      - ../_tmp:/app/uploads
    ports:
      - "8092:8092"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - consilient-net
    restart: unless-stopped