networks:
  consilient-net:
    driver: bridge
    name: consilient-net

volumes:
  consilient-mssql-data:

services:

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - consilient-net
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - consilient-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin" # change in production
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - loki
    networks:
      - consilient-net
    restart: unless-stopped

  db:
    image: ${DOCKER_REGISTRY-}consilientdb
    container_name: consilient.db.container
    build:
      context: .
      dockerfile: Db/Dockerfile
    ports:
      - "1434:1433"
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    command: -databases consilient_hangfire consilient_main
    volumes:
        - consilient-mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"${SA_PASSWORD}\" -C -Q \"SELECT 1\""]
      interval: 10s
      retries: 10
      start_period: 60s
      timeout: 3s
    networks:
      - consilient-net
    restart: unless-stopped

  consilient.webapp:
    image: ${DOCKER_REGISTRY-}consilientwebapp
    container_name: consilient.webapp.container
    build:
      context: ..
      dockerfile: Consilient.WebApp/Dockerfile
      args:
        BUILD_CONFIGURATION: "Debug"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - consilient-net

  consilient.api:
    image: ${DOCKER_REGISTRY-}consilientapi
    container_name: consilient.api.container
    build:
      context: ..
      dockerfile: Consilient.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: "Debug"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "8090:8090"
      - "8091:8091"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - consilient-net

  consilient.backgroundhost:
    image: ${DOCKER_REGISTRY-}consilientbackgroundhost
    container_name: consilient.backgroundhost.container
    build:
      context: ..
      dockerfile: Consilient.BackgroundHost/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8092"
    ports:
      - "8092:8092"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - consilient-net
    restart: unless-stopped